name: CI - Pickup Service

on:
  push:
    branches:
      - dev
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Set environment
        id: env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build & Push Image
    needs: setup
    uses: ravencalamitouss/devops-central/.github/workflows/build-push.yaml@main
    with:
      service_name: logistics-pickup
      environment: ${{ needs.setup.outputs.environment }}
      branch: ${{ github.ref_name }}
      sha: ${{ github.sha }}
    secrets: inherit

  update-helm:
    name: Update Helm Values
    needs: [setup, build]
    uses: ravencalamitouss/devops-central/.github/workflows/update-helm.yaml@main
    with:
      service_name: logistics-pickup
      environment: ${{ needs.setup.outputs.environment }}
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit